const translations = {
  en: {
    title: "Mr.Cartonix сoin (CARTONIX)",
    title2: "The cardboard hero's crypto adventure. Join the revolution!",
    title3: "What is CARTONIX?",
    title4: "Mr.Cartonix is not just a meme. It's a crypto movement! He started with a box factory, and now he has his own token, CARTONIX.",
    title5: "100% community-oriented",
    title6: "Meme, utility and fun",
    title7: "The mission is to show that the crypt can be fun and accessible.",
    title8: "Cryptocurrencies Price",
    title9: "Buy",
    title10: "Sell",
    title11: "Tokenomics",
    title12: "Total offer: 1,000,000,000 CARTONIX",
    title13: "Community and listing: 70% (700 mln)",
    title14: "Team and development: 30% (300 mln 250 million are blocked for 12 months)",
    title15: "NFT Collection SOON",
    title16: "Roadmap",
    title17: "Creation and launch of the CARTONIX token",
    title18: "Launching memes and videos on social media",
    title19: "Listing on DEX",
    title20: "Creating an NFT collection",
    title21: "Selling social media ads and buying CARTONIX tokens",
    title22: "Creating a Game with Mr.Cartonix",
    title23: "Our team",
    title24: "Mr.Cartonix — Creator",
    title25: "Soon — Developer on Solana",
    title26: "Soon — NFT-artist",
    title27: "Soon — Content maker",
    title28: "Frequently Asked Questions (FAQ)",
    title29: "How do I buy CARTONIX?",
    title30: "Click the buy button and buy a token for SOL.",
    title31: "Where can I store CARTONIX?",
    title32: "You can use Phantom wallets or any Solana-compatible ones.",
    title33: "When is the NFT launch?",
    title34: "The launch is scheduled for Q3 2025. Stay tuned on social media.",
    title35: "© 2025 Mr.Cartonix Coin — Powered by memes and blockchain",

  },

  ru: {
    title: "Mr.Cartonix монета (CARTONIX)",
    title2: "Крипто-приключение картонного героя. Присоединяйтесь к революции!",
    title3: "Что такое CARTONIX?",
    title4: "Mr.Cartonix - это не просто мем. Это криптодвижение! Он начинал с работы на фабрике по изготовлению коробок, а теперь у него есть свой собственный токен CARTONIX.",
    title5: "100% ориентированный на сообщество",
    title6: "Мем, полезность и веселье",
    title7: "Миссия состоит в том, чтобы показать, что крипта может быть веселой и доступной.",
    title8: "Цена криптовалюты",
    title9: "Купить",
    title10: "Продать",
    title11: "Токеномика",
    title12: "Общее предложение: 1,000,000,000 CARTONIX",
    title13: "Комьюнити и листинг: 70% (700 млн)",
    title14: "Команда и развитие: 30% (300 млн) - (250 миллионов заблокированы на 12 месяцев)",
    title15: "NFT Коллекция СКОРО",
    title16: "Дорожная карта",
    title17: "Создание и запуск токена CARTONIX",
    title18: "Запуск мемов и видеороликов в социальных сетях",
    title19: "Листинг на DEX",
    title20: "Создание NFT коллекции",
    title21: "Продажа рекламы в социальных сетях и покупка токенов CARTONIX",
    title22: "Создаем игру вместе с Mr.Cartonix",
    title23: "Наша команда",
    title24: "Mr.Cartonix — Создатель",
    title25: "Скоро - разработчик на Solana",
    title26: "Скоро - NFT-художник",
    title27: "Скоро - Создатель контента",
    title28: "Часто задаваемые вопросы (FAQ)",
    title29: "Как мне купить CARTONIX?",
    title30: "Нажмите кнопку Купить и купите токен за SOL.",
    title31: "Где я могу хранить CARTONIX?",
    title32: "Вы можете использовать Phantom кошелек или любые кошельки, совместимые с Solana.",
    title33: "Когда состоится запуск NFT?",
    title34: "Запуск запланирован на 4 квартал 2025 года. Следите за обновлениями в социальных сетях.",
    title35: "© 2025 Mr.Cartonix Coin — Работает на мемах и блокчейне",

  },

 es: {
  title: "Mr.Cartonix Coin (CARTONIX)",
  title2: "La aventura cripto del héroe de cartón. ¡Únete a la revolución!",
  title3: "¿Qué es CARTONIX?",
  title4: "Mr.Cartonix no es solo un meme. ¡Es un movimiento cripto! Comenzó con una fábrica de cajas, y ahora tiene su propio token, CARTONIX.",
  title5: "100% orientado a la comunidad",
  title6: "Meme, utilidad y diversión",
  title7: "La misión es demostrar que la cripto puede ser divertida y accesible.",
  title8: "Precio de criptomonedas",
  title9: "Comprar",
  title10: "Vender",
  title11: "Tokenomics",
  title12: "Oferta total: 1.000.000.000 CARTONIX",
  title13: "Comunidad y listado: 70% (700 millones)",
  title14: "Equipo y desarrollo: 30% (300 millones, 250 millones bloqueados por 12 meses)",
  title15: "Colección NFT PRONTO",
  title16: "Hoja de ruta",
  title17: "Creación y lanzamiento del token CARTONIX",
  title18: "Lanzamiento de memes y videos en redes sociales",
  title19: "Listado en DEX",
  title20: "Creación de una colección NFT",
  title21: "Venta de publicidad en redes sociales y compra de tokens CARTONIX",
  title22: "Creación de un juego con Mr.Cartonix",
  title23: "Nuestro equipo",
  title24: "Mr.Cartonix — Creador",
  title25: "Próximamente — Desarrollador en Solana",
  title26: "Próximamente — Artista NFT",
  title27: "Próximamente — Creador de contenido",
  title28: "Preguntas Frecuentes (FAQ)",
  title29: "¿Cómo compro CARTONIX?",
  title30: "Haz clic en el botón de compra y adquiere el token con SOL.",
  title31: "¿Dónde puedo guardar CARTONIX?",
  title32: "Puedes usar billeteras Phantom o cualquier otra compatible con Solana.",
  title33: "¿Cuándo es el lanzamiento del NFT?",
  title34: "Está programado para el tercer trimestre de 2025. Síguenos en redes sociales.",
  title35: "© 2025 Mr.Cartonix Coin — Impulsado por memes y blockchain"

},

  de: {
  title: "Mr.Cartonix Coin (CARTONIX)",
  title2: "Das Krypto-Abenteuer des Kartonhelden. Schließe dich der Revolution an!",
  title3: "Was ist CARTONIX?",
  title4: "Mr.Cartonix ist nicht nur ein Meme. Es ist eine Krypto-Bewegung! Er begann mit einer Kartonfabrik und hat jetzt seinen eigenen Token, CARTONIX.",
  title5: "100% gemeinschaftsorientiert",
  title6: "Meme, Nutzen und Spaß",
  title7: "Die Mission ist zu zeigen, dass Krypto Spaß machen und zugänglich sein kann.",
  title8: "Kryptowährungspreise",
  title9: "Kaufen",
  title10: "Verkaufen",
  title11: "Tokenomics",
  title12: "Gesamtangebot: 1.000.000.000 CARTONIX",
  title13: "Community und Listing: 70% (700 Mio)",
  title14: "Team und Entwicklung: 30% (300 Mio, 250 Mio gesperrt für 12 Monate)",
  title15: "NFT Kollektion BALD",
  title16: "Fahrplan",
  title17: "Erstellung und Start des CARTONIX-Tokens",
  title18: "Start von Memes und Videos in sozialen Netzwerken",
  title19: "Listing auf DEX",
  title20: "Erstellung einer NFT-Kollektion",
  title21: "Verkauf von Social-Media-Werbung und Kauf von CARTONIX-Token",
  title22: "Erstellung eines Spiels mit Mr.Cartonix",
  title23: "Unser Team",
  title24: "Mr.Cartonix — Gründer",
  title25: "Demnächst — Entwickler auf Solana",
  title26: "Demnächst — NFT-Künstler",
  title27: "Demnächst — Content Creator",
  title28: "Häufig gestellte Fragen (FAQ)",
  title29: "Wie kaufe ich CARTONIX?",
  title30: "Klicke auf den Kauf-Button und kaufe den Token mit SOL.",
  title31: "Wo kann ich CARTONIX speichern?",
  title32: "Du kannst Phantom oder jede Solana-kompatible Wallet verwenden.",
  title33: "Wann ist der NFT-Launch?",
  title34: "Geplant für Q3 2025. Bleibe auf Social Media auf dem Laufenden.",
  title35: "© 2025 Mr.Cartonix Coin — Angetrieben von Memes und Blockchain"

},

ar: {
  title: "عملة Mr.Cartonix (CARTONIX)",
  title2: "مغامرة كرتونية في عالم الكريبتو. انضم إلى الثورة!",
  title3: "ما هو CARTONIX؟",
  title4: "Mr.Cartonix ليس مجرد ميم. إنه حركة كريبتو! بدأ من مصنع صناديق، والآن يملك رمزه الخاص.",
  title5: "100٪ موجه للمجتمع",
  title6: "ميم، فائدة، ومتعة",
  title7: "المهمة هي إثبات أن الكريبتو يمكن أن يكون ممتعًا وسهل الوصول.",
  title8: "أسعار العملات الرقمية",
  title9: "شراء",
  title10: "بيع",
  title11: "الرموز الاقتصادية",
  title12: "الإجمالي المعروض: 1,000,000,000 CARTONIX",
  title13: "المجتمع والإدراج: 70٪ (700 مليون)",
  title14: "الفريق والتطوير: 30٪ (300 مليون، 250 مليون مقفلة لمدة 12 شهرًا)",
  title15: "مجموعة NFT قريبا",
  title16: "خارطة الطريق",
  title17: "إنشاء وإطلاق رمز CARTONIX",
  title18: "إطلاق الميمات والفيديوهات على وسائل التواصل",
  title19: "إدراج على DEX",
  title20: "إنشاء مجموعة NFT",
  title21: "بيع إعلانات التواصل الاجتماعي وشراء رموز CARTONIX",
  title22: "إنشاء لعبة مع Mr.Cartonix",
  title23: "فريقنا",
  title24: "Mr.Cartonix — المؤسس",
  title25: "قريبًا — مطور على سولانا",
  title26: "قريبًا — فنان NFT",
  title27: "قريبًا — صانع محتوى",
  title28: "الأسئلة الشائعة",
  title29: "كيف أشتري CARTONIX؟",
  title30: "اضغط على زر الشراء واشترِ الرمز باستخدام SOL.",
  title31: "أين يمكنني حفظ CARTONIX؟",
  title32: "يمكنك استخدام محفظة Phantom أو أي محفظة متوافقة مع سولانا.",
  title33: "متى سيتم إطلاق NFT؟",
  title34: "من المقرر إطلاقه في الربع الثالث من 2025. تابعنا على السوشيال ميديا.",
  title35: "© 2025 عملة Mr.Cartonix — مدعوم بالميمز والبلوكشين"
},

hi: {
  title: "Mr.Cartonix Coin (CARTONIX)",
  title2: "कार्डबोर्ड हीरो की क्रिप्टो यात्रा। क्रांति में शामिल हों!",
  title3: "CARTONIX क्या है?",
  title4: "Mr.Cartonix सिर्फ एक मीम नहीं है। यह एक क्रिप्टो आंदोलन है! उन्होंने एक डब्बा फैक्ट्री से शुरुआत की थी और अब उनका खुद का टोकन है — CARTONIX।",
  title5: "100% समुदाय-उन्मुख",
  title6: "मीम, उपयोगिता और मज़ा",
  title7: "मिशन है दिखाना कि क्रिप्टो मजेदार और सबके लिए सुलभ हो सकता है।",
  title8: "क्रिप्टोकरेंसी कीमतें",
  title9: "खरीदें",
  title10: "बेचें",
  title11: "टोकनोमिक्स",
  title12: "कुल आपूर्ति: 1,000,000,000 CARTONIX",
  title13: "समुदाय और लिस्टिंग: 70% (700 मिलियन)",
  title14: "टीम और विकास: 30% (300 मिलियन में से 250 मिलियन 12 महीनों के लिए ब्लॉक किए गए हैं)",
  title15: "NFT संग्रह जल्द ही",
  title16: "रोडमैप",
  title17: "CARTONIX टोकन का निर्माण और लॉन्च",
  title18: "सोशल मीडिया पर मीम्स और वीडियो लॉन्च करना",
  title19: "DEX पर लिस्टिंग",
  title20: "NFT संग्रह बनाना",
  title21: "सोशल मीडिया विज्ञापन बेचना और CARTONIX टोकन खरीदना",
  title22: "Mr.Cartonix के साथ एक गेम बनाना",
  title23: "हमारी टीम",
  title24: "Mr.Cartonix — निर्माता",
  title25: "जल्द ही — Solana पर डेवलपर",
  title26: "जल्द ही — NFT कलाकार",
  title27: "जल्द ही — कंटेंट निर्माता",
  title28: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
  title29: "मैं CARTONIX कैसे खरीदूं?",
  title30: "खरीद बटन पर क्लिक करें और SOL से टोकन खरीदें।",
  title31: "मैं CARTONIX कहां स्टोर कर सकता हूं?",
  title32: "आप Phantom या कोई भी Solana-संगत वॉलेट उपयोग कर सकते हैं।",
  title33: "NFT लॉन्च कब है?",
  title34: "लॉन्च Q3 2025 के लिए निर्धारित है। सोशल मीडिया पर नजर रखें।",
  title35: "© 2025 Mr.Cartonix Coin — मीम्स और ब्लॉकचेन द्वारा संचालित"
},
  cn:{
    title: "纸箱先生币 (CARTONIX)",
    title2: "纸箱英雄的加密冒险。加入这场革命吧！",
    title3: "什么是 CARTONIX？",
    title4: "纸箱先生不仅仅是一个迷因。它是一场加密运动！他从一个纸箱工厂起家，现在有了自己的代币，CARTONIX。",
    title5: "100% 社区驱动",
    title6: "迷因、实用性和乐趣",
    title7: "我们的使命是证明加密货币可以充满乐趣且易于使用。",
    title8: "加密货币价格",
    title9: "购买",
    title10: "出售",
    title11: "代币经济学",
    title12: "总供应量：1,000,000,000 CARTONIX",
    title13: "社区和上市：70% (7 亿)",
    title14: "团队和开发：30% (3 亿，其中 2.5 亿将被锁定 12 个月)",
    title15: "NFT 系列 即将推出",
    title16: "路线图",
    title17: "创建和发行 CARTONIX 代币",
    title18: "在社交媒体上发布迷因和视频",
    title19: "在 DEX 上市",
    title20: "创建 NFT 系列",
    title21: "销售社交媒体广告并购买 CARTONIX 代币",
    title22: "创建一个以纸箱先生为主角的游戏",
    title23: "我们的团队",
    title24: "纸箱先生 — 创始人",
    title25: "即将加入 — Solana 开发者",
    title26: "即将加入 — NFT 艺术家",
    title27: "即将加入 — 内容创作者",
    title28: "常见问题解答 (FAQ)",
    title29: "如何购买 CARTONIX？",
    title30: "点击购买按钮，使用 SOL 购买代币。",
    title31: "在哪里可以存储 CARTONIX？",
    title32: "您可以使用 Phantom 钱包或任何与 Solana 兼容的钱包。",
    title33: "NFT 何时发布？",
    title34: "预计在 2025 年第三季度发布。请关注我们的社交媒体。",
    title35: "© 2025 纸箱先生币 — 由迷因和区块链驱动"
}

};

function updateLanguage(lang) {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });
}

document.addEventListener("DOMContentLoaded", () => {
  const select = document.getElementById("languageSelect");
  updateLanguage(select.value);
  select.addEventListener("change", () => {
    updateLanguage(select.value);
  });
});
